[build]
  ignore = "/bin/false"
  base = ".nxc"
  publish = "./output"
  command = "rm -rf \"NETLIFY_BUILD_BASE/.cache\" && nxc build -i .. -o ./output --lunr --commits"

[build.environment]
  PYTHON_VERSION = "3.8"
